[package]
name = "Sierpinski_Triangle"
version = "0.1.0"
authors = ["Biywcoms <biywcoms@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
rand = "*"
